import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";

export default function WriteReview() {
  const navigate = useNavigate(); const [restaurants, setRestaurants] = useState([]); const [form, setForm] = useState({ restaurant: "", rating: 5, comment: "" }); const [message, setMessage] = useState("");
  useEffect(() => { api.get("/restaurants").then(({ data }) => setRestaurants(data.restaurants)).catch(() => {}); }, []);
  const submit = async (event) => { event.preventDefault(); if (!localStorage.getItem("token")) return navigate("/login"); try { const { data } = await api.post("/reviews", form); setMessage(data.message); setForm({ restaurant: "", rating: 5, comment: "" }); } catch (error) { setMessage(error.response?.data?.message || "Unable to submit review."); } };
  return <section className="py-20 bg-white"><div className="text-center mb-12"><h2 className="text-4xl font-bold text-orange-600">Write a Review</h2><p className="text-gray-600 mt-3">We'd love to hear about your dining experience.</p></div><div className="max-w-4xl mx-auto bg-gray-100 rounded-xl shadow-lg p-8"><form onSubmit={submit} className="space-y-6"><div className="grid md:grid-cols-2 gap-6"><select required value={form.restaurant} onChange={(e) => setForm({ ...form, restaurant: e.target.value })} className="border rounded-lg p-3"><option value="">Select Restaurant</option>{restaurants.map((restaurant) => <option key={restaurant._id} value={restaurant._id}>{restaurant.name}</option>)}</select><select value={form.rating} onChange={(e) => setForm({ ...form, rating: Number(e.target.value) })} className="border rounded-lg p-3">{[5,4,3,2,1].map((rating) => <option key={rating} value={rating}>{"⭐".repeat(rating)} ({rating})</option>)}</select></div><textarea required rows="6" value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} placeholder="Share your dining experience..." className="w-full border rounded-lg p-3" />{message && <p className="text-center text-orange-700">{message}</p>}<button type="submit" className="w-full bg-orange-600 text-white py-3 rounded-lg hover:bg-orange-700">Submit Review</button></form></div></section>;
}
