import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import api from "../services/api";

const emptyForm = { fullName: "", restaurantName: "", ownerName: "", fssaiNumber: "", email: "", phone: "", city: "", area: "", image: "", password: "", confirmPassword: "" };

export default function Register() {
  const navigate = useNavigate(); const [accountType, setAccountType] = useState("customer"); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(""); const set = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => {
    event.preventDefault(); setError("");
    if (form.password !== form.confirmPassword) return setError("Passwords do not match.");
    const payload = accountType === "restaurant" ? { name: form.ownerName, email: form.email, password: form.password, role: "restaurant", restaurantName: form.restaurantName, ownerName: form.ownerName, fssaiNumber: form.fssaiNumber || undefined, city: form.city, area: form.area, image: form.image, phone: form.phone } : { name: form.fullName, email: form.email, password: form.password, role: "customer", phone: form.phone };
    try { const { data } = await api.post("/auth/register", payload); alert(`${data.message}. Please log in.`); navigate("/login"); } catch (requestError) { setError(requestError.response?.data?.message || "Registration failed."); }
  };
  const input = (name, label, type = "text", required = true, placeholder = "") => <label className="block"><span className="block mb-2 font-medium">{label}</span><input required={required} type={type} name={name} value={form[name]} onChange={set} placeholder={placeholder} className="w-full border rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-orange-500" /></label>;
  return <div className="min-h-screen bg-orange-50 flex items-center justify-center px-4 py-10"><div className="bg-white shadow-xl rounded-2xl p-8 w-full max-w-2xl"><h1 className="text-3xl font-bold text-center text-orange-600 mb-2">Create Account</h1><p className="text-center text-gray-500 mb-8">Join TableReserve as a diner or restaurant owner.</p>
    <div className="flex mb-5 border rounded-lg overflow-hidden"><button type="button" onClick={() => setAccountType("customer")} className={`w-1/2 py-3 font-semibold ${accountType === "customer" ? "bg-orange-600 text-white" : "bg-white"}`}>Customer</button><button type="button" onClick={() => setAccountType("restaurant")} className={`w-1/2 py-3 font-semibold ${accountType === "restaurant" ? "bg-orange-600 text-white" : "bg-white"}`}>Restaurant</button></div>
    {accountType === "restaurant" && <div className="mb-6 rounded-lg bg-amber-50 border border-amber-200 p-4 text-sm text-amber-900"><strong>Educational demo only.</strong><p className="mt-1">Use fictional restaurant and contact information. Do not submit a real GSTIN, FSSAI licence, identity document, banking information, or confidential business data. Demo restaurants remain hidden until administrator approval.</p></div>}
    <form className="space-y-5" onSubmit={submit}>{accountType === "customer" ? <div className="grid md:grid-cols-2 gap-5">{input("fullName", "Full Name")}{input("email", "Email address", "email")}{input("phone", "Mobile number", "tel")}</div> : <><h2 className="font-bold text-xl text-gray-800">Demo restaurant registration</h2><div className="grid md:grid-cols-2 gap-5">{input("restaurantName", "Fictional restaurant name")}{input("ownerName", "Fictional owner name")}{input("fssaiNumber", "Demo FSSAI reference (optional)", "text", false, "Use fictional digits only")}{input("email", "Demo business email", "email")}{input("phone", "Demo mobile number", "tel")}{input("city", "City")}{input("area", "Area")}</div>{input("image", "Licensed restaurant image URL", "url")}<label className="flex items-start gap-3 rounded-lg border border-orange-200 bg-orange-50 p-4 text-sm text-gray-700"><input required type="checkbox" className="mt-1 h-4 w-4 accent-orange-600" /><span>I confirm that I am submitting fictional demo information only and that I have permission to use the restaurant image.</span></label></>}
      <div className="grid md:grid-cols-2 gap-5">{input("password", "Create password", "password")}{input("confirmPassword", "Confirm password", "password")}</div>{error && <p className="text-red-600 text-center">{error}</p>}<button type="submit" className="w-full bg-orange-600 text-white py-3 rounded-lg hover:bg-orange-700">{accountType === "restaurant" ? "Register Restaurant" : "Create Customer Account"}</button></form><p className="text-center mt-6 text-gray-600">Already have an account? <Link to="/login" className="text-orange-600 font-semibold hover:underline">Login</Link></p>
  </div></div>;
}
