import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";

export default function RestaurantDashboard() {
  const navigate = useNavigate(); const [data, setData] = useState(null); const [error, setError] = useState("");
  const load = async () => { try { const response = await api.get("/restaurants/owner/dashboard"); setData(response.data); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to load your dashboard."); } };
  useEffect(() => { const user = JSON.parse(localStorage.getItem("user") || "null"); if (!user) { navigate("/login"); return undefined; } if (user.role !== "restaurant") { navigate("/"); return undefined; } const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [navigate]);
  const updateBooking = async (id, status) => { try { await api.patch(`/restaurants/owner/reservations/${id}`, { status }); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to update booking."); } };
  if (error) return <main className="min-h-screen p-12 text-center text-red-600">{error}</main>; if (!data) return <main className="min-h-screen p-12 text-center">Loading dashboard...</main>;
  const cards = [["Total bookings", data.metrics.totalBookings], ["Pending requests", data.metrics.pendingRequests], ["Confirmed", data.metrics.confirmedBookings], ["Estimated booking revenue", `₹${data.metrics.estimatedRevenue.toLocaleString("en-IN")}`]];
  return <main className="min-h-screen bg-orange-50 px-6 py-12"><div className="max-w-6xl mx-auto"><div className="mb-8"><p className="text-orange-600 font-semibold">Restaurant owner dashboard</p><h1 className="text-4xl font-bold">{data.restaurant.name}</h1><p className="text-gray-600">{data.restaurant.city}, {data.restaurant.area}</p></div><section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-10">{cards.map(([label, value]) => <article key={label} className="bg-white shadow rounded-xl p-5"><p className="text-gray-500">{label}</p><p className="text-3xl font-bold text-orange-600 mt-2">{value}</p></article>)}</section><section className="bg-white shadow rounded-xl overflow-hidden"><div className="p-6 border-b"><h2 className="text-2xl font-bold">Customer table requests</h2></div>{data.reservations.length ? <div className="divide-y">{data.reservations.map((booking) => <article key={booking._id} className="p-6 flex flex-col md:flex-row gap-4 md:items-center md:justify-between"><div><h3 className="font-bold text-lg">{booking.user?.name || "Customer"}</h3><p className="text-gray-600">{booking.user?.email} · {booking.user?.phone || "No phone"}</p><p className="text-gray-600 mt-1">{booking.date} at {booking.time} · {booking.guests} guests</p></div><div className="flex items-center gap-3"><span className="capitalize font-semibold text-orange-700">{booking.status}</span>{booking.status === "pending" && <><button onClick={() => updateBooking(booking._id, "confirmed")} className="bg-green-600 text-white px-4 py-2 rounded-lg">Confirm</button><button onClick={() => updateBooking(booking._id, "declined")} className="border border-red-500 text-red-600 px-4 py-2 rounded-lg">Decline</button></>}</div></article>)}</div> : <p className="p-6 text-gray-500">No booking requests yet.</p>}</section></div></main>;
}
